src/Masuit.MyBlogs.WebApp/Controllers/NoticeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web.Mvc;
using Common;
using IBLL;
using Masuit.MyBlogs.WebApp.Models;
using Masuit.Tools;
using Masuit.Tools.Html;
using Masuit.Tools.Net;
using Models.DTO;
using Models.Entity;
using Models.Enum;

namespace Masuit.MyBlogs.WebApp.Controllers
{
    public class NoticeController : BaseController
    {
        public INoticeBll NoticeBll { get; set; }

        public NoticeController(INoticeBll noticeBll)
        {
            NoticeBll = noticeBll;
        }

        [Route("notice")]
        public ActionResult Index(int page = 1, int size = 10, int id = 0)
        {
            UserInfoOutputDto user = Session.GetByRedis<UserInfoOutputDto>(SessionKey.UserInfo);
            List<NoticeOutputDto> list;
            int total;
            if (user != null && user.IsAdmin)
            {
                if (id != 0)
                {
                    Notice notice = NoticeBll.GetById(id);
                    ViewBag.Total = 1;
                    return View("Index_Admin", new List<NoticeOutputDto> { notice.MapTo<NoticeOutputDto>() });
                }
                list = NoticeBll.LoadPageEntitiesNoTracking<DateTime, NoticeOutputDto>(page, size, out total, n => n.Status == Status.Display, n => n.ModifyDate, false).ToList();
                ViewBag.Total = total;
                return View("Index_Admin", list);
            }
            list = NoticeBll.LoadPageEntitiesNoTracking<DateTime, NoticeOutputDto>(page, size, out total, n => n.Status == Status.Display, n => n.ModifyDate, false).ToList();
            ViewBag.Total = total;
            return View(list);
        }

        [Route("n/{id:int}")]
        public ActionResult Details(int id)
        {
            Notice notice = NoticeBll.GetById(id);
            if (notice != null)
            {
                return View(notice);
            }
            return RedirectToAction("Index");
        }

        [ValidateInput(false), Authority]
        public ActionResult Write(Notice notice)
        {
            notice.Content = CommonHelper.ReplaceImgSrc(Regex.Replace(notice.Content, @"<img\s+[^>]*\s*src\s*=\s*['""]?(\S+\.\w{3,4})['""]?[^/>]*/>", "<img src=\"$1\"/>")).Replace("/thumb150/", "/large/");
            Notice e = NoticeBll.AddEntitySaved(notice);
            if (e != null)
            {
                return ResultData(null, message: "发布成功");
            }
            return ResultData(null, false, "发布失败");
        }

        [Authority]
        public ActionResult Delete(int id)
        {
            var post = NoticeBll.GetById(id);
            if (post is null)
            {
                return ResultData(null, false, "公告已经被删除！");
            }

            var mc = post.Content.MatchImgTags();
            foreach (Match m in mc)
            {
                string path = m.Groups[3].Value;
                if (path.StartsWith("/"))
                {
                    path = Path.Combine(Server.MapPath("/"), path);
                    try
                    {
                        System.IO.File.Delete(path);
                    }
                    catch
                    {
                    }
                }
            }
            bool b = NoticeBll.DeleteByIdSaved(id);
            return ResultData(null, b, b ? "删除成功" : "删除失败");
        }

        [ValidateInput(false), Authority]
        public ActionResult Edit(Notice notice)
        {
            Notice entity = NoticeBll.GetById(notice.Id);
            entity.ModifyDate = DateTime.Now;
            entity.Title = notice.Title;
            entity.Content = CommonHelper.ReplaceImgSrc(Regex.Replace(notice.Content, @"<img\s+[^>]*\s*src\s*=\s*['""]?(\S+\.\w{3,4})['""]?[^/>]*/>", "<img src=\"$1\"/>")).Replace("/thumb150/", "/large/");
            bool b = NoticeBll.UpdateEntitySaved(entity);
            return ResultData(null, b, b ? "修改成功" : "修改失败");
        }

        public ActionResult GetPageData(int page = 1, int size = 10)
        {
            List<Notice> list = NoticeBll.LoadPageEntitiesNoTracking(page, size, out int total, n => true, n => n.ModifyDate, false).ToList();
            var pageCount = Math.Ceiling(total * 1.0 / size).ToInt32();
            return PageResult(list, pageCount, total);
        }

        public ActionResult Get(int id)
        {
            Notice notice = NoticeBll.GetById(id);
            if (Session["notice" + id] is null)
            {
                notice.ViewCount++;
                NoticeBll.UpdateEntitySaved(notice);
                Session["notice" + id] = id;
            }
            return ResultData(notice.MapTo<NoticeOutputDto>());
        }

        public ActionResult Last()
        {
            var notice = NoticeBll.GetFirstEntityFromL2Cache(n => n.Status == Status.Display, n => n.ModifyDate, false);
            if (notice != null)
            {
                if (Session["notice" + notice.Id] is null)
                {
                    notice.ViewCount++;
                    NoticeBll.UpdateEntitySaved(notice);
                    Session["notice" + notice.Id] = +notice.Id;
                }
                return ResultData(notice.Mapper<NoticeOutputDto>());
            }
            return ResultData(null, false);
        }
    }
}

src/Masuit.MyBlogs.WebApp/Views/Notice/Details.cshtml
@using System.Text.RegularExpressions
@using Common
@using Masuit.MyBlogs.WebApp.Models
@using Masuit.Tools.Net
@using Models.DTO
@model Models.Entity.Notice
@{
    ViewBag.Title = Model.Title;
    Layout = "~/Views/Shared/_Layout.cshtml";
    Random r = new Random();
}
<style>
    .bg-title {
        height: 400px;
        position: relative;
        background: url(/Content/images/@(r.Next(1, 9)).jpg) no-repeat center;
        background-size: cover;
        background-attachment: fixed;
    }
    .header-content {
        position: absolute;
        left: 50%;
        top: 50%;
        transform: translate(-50%, -50%);
    }
    .header-content .divider {
        width: inherit;
        height: 20px;
        margin-top: 20px;
        border-top: 3px solid rebeccapurple;
    }
</style>
<ol class="cd-breadcrumb triangle">
    <li>@Html.ActionLink("首页", "Index", "Home")</li>
    <li>@Html.ActionLink("公告列表", "Index", "Notice")</li>
    <li class="current"><em>@ViewBag.Title</em></li>
</ol>
<div class="bg-title">
    <div class="header-content text-center">
        <h1 class="size48">
            @Model.Title
        </h1>
        <div class="divider"></div>
        <p class="size24">
            发布于：@Model.PostDate.ToString("yyyy-MM-dd") | 修改于：@Model.ModifyDate.ToString("yyyy-MM-dd") | 浏览人数：@Model.ViewCount
        </p>
    </div>
</div>
<div class="container">
    <div class="wrapper-content article">
        <div class="ibox">
            <div class="ibox-content">
                <section class="wow fadeInUp">
                    <div class="btn-group">
                        @Html.ActionLink("<<返回公告列表页", "Index", "Notice", null, new { @class = "btn btn-info" })
                        @{
                UserInfoOutputDto user = Session.GetByRedis<UserInfoOutputDto>(SessionKey.UserInfo) ?? new UserInfoOutputDto();
                if (user.IsAdmin)
                {
                    <a class="btn btn-primary" href="/dashboard#/notice/index?id=@Model.Id" target="_blank">修改</a>
    }
                        }
                    </div>
                </section>
                <hr class="margin-top10 marginbot10" />
                <main>
                    <section>
                        <article class="article" id="article">
                            @MvcHtmlString.Create(Regex.Replace(Model.Content, @"<img\s+[^>]*\s*src\s*=\s*['""]?(\S+\.\w{3,4})['""]?[^/>]*/>", $"<img data-original=\"$1\" alt='{CommonHelper.GetSettings("Title")}' title='{CommonHelper.GetSettings("Title")}'/>"))
                        </article>
                    </section>
                </main>
                <!--PC和WAP自适应版-->
                <div id="SOHUCS" sid="about/@Model.Id"></div>
                <script type="text/javascript">
	                (function() {
		                var appid = 'cytsT3QgK';
		                var conf = 'prod_0358240040a6c9611add9de991099d42';
		                var width = window.innerWidth || document.documentElement.clientWidth;
		                if (width < 960) {
			                window.document.write(
				                '<script id="changyan_mobile_js" charset="utf-8" type="text/javascript" src="https://changyan.sohu.com/upload/mobile/wap-js/changyan_mobile.js?client_id=' +
				                appid + '&conf=' + conf + '"><\/script>');
		                } else {
			                var loadJs = function(d, a) {
				                var c = document.getElementsByTagName("head")[0] || document.head || document.documentElement;
				                var b = document.createElement("script");
				                b.setAttribute("type", "text/javascript");
				                b.setAttribute("charset", "UTF-8");
				                b.setAttribute("src", d);
				                if (typeof a === "function") {
					                if (window.attachEvent) {
						                b.onreadystatechange = function() {
							                var e = b.readyState;
							                if (e === "loaded" || e === "complete") {
								                b.onreadystatechange = null;
								                a()
							                }
						                }
					                } else {
						                b.onload = a
					                }
				                }
				                c.appendChild(b)
			                };
			                loadJs("https://changyan.sohu.com/upload/changyan.js", function() {
				                window.changyan.api.config({
					                appid: appid,
					                conf: conf
				                })
			                });
		                }
	                })();
                </script>
            </div>
        </div>
    </div>
</div>

src/Masuit.MyBlogs.WebApp/Views/Notice/Index.cshtml
@using System.Text.RegularExpressions
@using Common
@using Models.DTO
@model IList<NoticeOutputDto>
@{
    ViewBag.Title = "网站公告栏";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Assets/timeline.css" rel="stylesheet" />
<link href="~/Assets/UEditor/third-party/SyntaxHighlighter/styles/shCore.min.css" rel="stylesheet" />
<div class="container min-height780">
    <ol class="cd-breadcrumb triangle">
        <li>@Html.ActionLink("首页", "Index", "Home")</li>
        <li class="current"><em>@ViewBag.Title</em></li>
    </ol>
    @{
        Html.RenderPartial("_Pagination");
    }
    <div class="row">
        <div class="col-md-12">
            <div class="main-timeline">
                @foreach(NoticeOutputDto n in Model) {
                    <div class="timeline">
                        <div class="timeline-content">
                            <div class="circle"><span><i class="fa fa-globe"></i></span>
                            </div>
                            <div class="content">
                                <span class="year">@n.PostDate.ToString("yyyy-MM-dd HH:mm:ss")</span>
                                <h4 class="title">@n.Title</h4>
                                <p class="description">
                                    <a href="/n/@n.Id" class="tippy-scale" title="查看详情">@MvcHtmlString.Create(Regex.Replace(n.Content, "\\s(title|alt)=['\"].+?['\"]", String.Empty).Replace("img src=", $"img title='{CommonHelper.GetSettings("Title")}' data-original="))</a>
                                </p>
                                <div class="icon"><span></span>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    @{
        Html.RenderPartial("_Pagination");
    }
		       
</div>
<script src="~/Assets/UEditor/third-party/SyntaxHighlighter/scripts/shCore.min.js"></script>
<script src="~/Assets/UEditor/third-party/SyntaxHighlighter/scripts/bundle.min.js"></script>
<script>
    SyntaxHighlighter.all();
    SyntaxHighlighter.defaults['toolbar'] = false;
</script>

src/Masuit.MyBlogs.WebApp/Views/Notice/Index_Admin.cshtml
@using Models.DTO
@model IList<NoticeOutputDto>
@{
    ViewBag.Title = "网站公告栏";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Assets/timeline.css" rel="stylesheet" />
<link href="~/Assets/UEditor/third-party/SyntaxHighlighter/styles/shCore.min.css" rel="stylesheet" />
<div class="container min-height780">
    <ol class="cd-breadcrumb triangle">
        <li>@Html.ActionLink("首页", "Index", "Home")</li>
        <li class="current"><em>@ViewBag.Title</em></li>
    </ol>
    @{
        Html.RenderPartial("_Pagination");
    }
    <a href="/dashboard#/notice/index" class="btn btn-info">发布新公告</a>
    <div class="row">
        <div class="col-md-12">
            <div class="main-timeline">
                @foreach(NoticeOutputDto n in Model) {
                    <div class="timeline">
                        <div class="timeline-content">
                            <div class="circle"><span><i class="fa fa-globe"></i></span>
                            </div>
                            <div class="content">
                                <span class="year">@n.PostDate.ToString("yyyy-MM-dd HH:mm:ss")</span>
                                <div class="title">
                                    <span>@n.Title</span>
                                    <div class="btn-group">
                                        <button class="btn btn-danger" onclick="del(@n.Id,'@n.Title')">删除</button>
                                        <a class="btn btn-info" href="/dashboard#/notice/index?id=@n.Id" target="_blank">修改</a>
                                    </div>
                                </div> 
                                <p class="description">
                                    <a href="/n/@n.Id" class="tippy-scale" title="查看详情">@MvcHtmlString.Create(n.Content)</a>
                                </p>
                                <div class="icon"><span></span>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    @{
        Html.RenderPartial("_Pagination");
    }
</div>
<script src="~/Assets/UEditor/third-party/SyntaxHighlighter/scripts/shCore.min.js"></script>
<script src="~/Assets/UEditor/third-party/SyntaxHighlighter/scripts/bundle.min.js"></script>
<script>
    SyntaxHighlighter.all();
    SyntaxHighlighter.defaults['toolbar'] = false;
	function del(id,title) {
        swal({
            title: "确认删除这条公告吗？",
            text: title,
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "确定",
            cancelButtonText: "取消",
            showLoaderOnConfirm: true,
            animation: true,
            allowOutsideClick: false
        }).then(function () {
            $.post("/notice/delete", {
                id: id
            }, function (data) {
                window.notie.alert({
                    type: 1,
                    text: data.Message,
                    time: 4
                });
                window.location.reload();
            });
        }, function () {
        });
	}
</script>