src/Masuit.MyBlogs.WebApp/Controllers/BugController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web.Mvc;
using Common;
using Hangfire;
using IBLL;
using Masuit.MyBlogs.WebApp.Models;
using Masuit.Tools.Net;
using Masuit.Tools.Systems;
using Models.DTO;
using Models.Entity;
using Models.Enum;

namespace Masuit.MyBlogs.WebApp.Controllers
{
    public class BugController : BaseController
    {
        public IIssueBll IssueBll { get; set; }
        public IInternalMessageBll MessageBll { get; set; }

        public BugController(IIssueBll issueBll, IInternalMessageBll messageBll)
        {
            IssueBll = issueBll;
            MessageBll = messageBll;
        }

        [Route("bug")]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult PageData(int page = 1, int size = 10, string kw = "")
        {
            UserInfoOutputDto user = Session.GetByRedis<UserInfoOutputDto>(SessionKey.UserInfo) ?? new UserInfoOutputDto();
            List<Issue> list = string.IsNullOrEmpty(kw) ? IssueBll.LoadPageEntitiesNoTracking(page, size, out int total, i => i.Level != BugLevel.Fatal || user.IsAdmin, i => i.SubmitTime, false).ToList() : IssueBll.LoadPageEntitiesNoTracking(page, size, out total, i => (i.Level != BugLevel.Fatal || user.IsAdmin) && (i.Description.Contains(kw) || i.Title.Contains(kw) || i.Name.Contains(kw) || i.Email.Contains(kw) || i.Link.Contains(kw)), i => i.SubmitTime, false).ToList();
            var pageCount = Math.Ceiling(total * 1.0 / size).ToInt32();
            return PageResult(list.Select(i => new
            {
                i.Id,
                i.Name,
                i.Email,
                i.Title,
                i.Link,
                i.Description,
                i.SubmitTime,
                i.HandleTime,
                Status = i.Status.GetDisplay(),
                Level = i.Level.GetDisplay()
            }), pageCount, total);
        }

        [Route("bug/{id:int}")]
        public ActionResult Datails(int id)
        {
            Issue issue = IssueBll.GetById(id);
            if (issue is null)
            {
                return RedirectToAction("Index", "Error");
            }
            return View(issue);
        }

        [Authority]
        public ActionResult Handle(int id, string text)
        {
            Issue issue = IssueBll.GetById(id);
            issue.Status = Status.Handled;
            issue.HandleTime = DateTime.Now;
            issue.Msg = text;
            bool b = IssueBll.UpdateEntitySaved(issue);
            string content = System.IO.File.ReadAllText(Request.MapPath("/template/bugfeed.html")).Replace("{{title}}", issue.Title).Replace("{{link}}", issue.Link).Replace("{{text}}", text).Replace("{{date}}", issue.HandleTime.Value.ToString("yyyy-MM-dd HH:mm:ss"));
            BackgroundJob.Enqueue(() => CommonHelper.SendMail("bug提交反馈通知", content, issue.Email));
            return ResultData(null, b, b ? "问题处理成功！" : "处理失败！");
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult Submit(Issue issue)
        {
            issue.Description = Regex.Replace(issue.Description, @"<img\s+[^>]*\s*src\s*=\s*['""]?(\S+\.\w{3,4})['""]?[^/>]*/>", "<img src=\"$1\"/>");
            issue.IPAddress = Request.UserHostAddress;
            Issue bug = IssueBll.AddEntitySaved(issue);
            if (bug != null)
            {
                MessageBll.AddEntitySaved(new InternalMessage()
                {
                    Title = $"来自【{issue.Name}({issue.Email})】的bug问题反馈",
                    Content = bug.Description,
                    Link = Url.Action("Index")
                });
                string content = System.IO.File.ReadAllText(Request.MapPath("/template/bugreport.html")).Replace("{{name}}", bug.Name).Replace("{{email}}", bug.Email).Replace("{{title}}", bug.Title).Replace("{{desc}}", bug.Description).Replace("{{link}}", bug.Link).Replace("{{date}}", bug.SubmitTime.ToString("yyyy-MM-dd HH:mm:ss"));
                BackgroundJob.Enqueue(() => CommonHelper.SendMail("bug提交通知", content, "admin@masuit.com"));
                return ResultData(issue, true, "问题提交成功，感谢您的反馈！");
            }
            return ResultData(null, false, "提交失败！");
        }

        [Authority]
        public ActionResult Delete(int id)
        {
            bool b = IssueBll.DeleteByIdSaved(id);
            return ResultData(null, b, b ? "删除成功！" : "删除失败！");
        }

        public ActionResult GetBugLevels()
        {
            List<object> list = new List<object>();
            foreach (Enum value in Enum.GetValues(typeof(BugLevel)))
            {
                list.Add(new
                {
                    name = value.GetDisplay(),
                    value
                });
            }
            return ResultData(list);
        }
    }
}

src/Masuit.MyBlogs.WebApp/Views/Bug/Datails.cshtml
@using System.Text.RegularExpressions
@using Common
@using Masuit.Tools.Systems
@using Models.Entity
@using Models.Enum
@model Issue
@{
    ViewBag.Title = Model.Title;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <ol class="cd-breadcrumb triangle">
        <li>@Html.ActionLink("首页", "Index", "Home")</li>
        <li>@Html.ActionLink("提交网站漏洞和BUG", "Index", "Bug")</li>
        <li class="current">
            <em>@ViewBag.Title</em>
        </li>
    </ol>
    <div class="wrapper-content article">
        <div class="ibox">
            <div class="ibox-content">
                <main>
                    <section>
                        <header class="page-header">
                            <div class="text-center">
                                <a>
                                    <h3 class="padding-bot10">
                                        存在的问题：@Model.Title
                                    </h3>
                                </a>
                            </div>
                            <div class="row">
                                <div class="col-sm-9">
                                    <div class="padding-bot10">
                                        提交人：<span class="label label-info">@Model.Name (@Model.Email)</span> | 提交时间：<span class="label label-danger">@Model.SubmitTime.ToString("yyyy-MM-dd HH:mm")</span> | 问题级别：<span class="label label-danger">@Model.Level.GetDisplay()</span>
                                    </div>
                                </div>
                                <div class="pull-right margin-right20">
                                    @if(Model.Status == Status.WaitingHandle) {
                                        <span class="label label-danger">@Model.Status.GetDisplay()</span>
                                    } else {
                                        <span class="label label-success">@Model.Status.GetDisplay()</span><span> 处理时间：<span class="label label-success">@Model.HandleTime.Value.ToString("yyyy-MM-dd HH:mm")</span></span>
                                    }
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    存在问题的链接：<a href="@Model.Link">@Model.Link</a>
                                </div>
                            </div>
                        </header>
                        <article class="article" id="article">
                            <h3>问题详细描述：</h3>
                            @MvcHtmlString.Create(Regex.Replace(Model.Description, @"<img\s+[^>]*\s*src\s*=\s*['""]?(\S+\.\w{3,4})['""]?[^/>]*/>", $"<img data-original=\"$1\" alt='{CommonHelper.GetSettings("Title")}' title='{CommonHelper.GetSettings("Title")}'/>"))
                        </article>
                    </section>
                </main>
                @if(Model.Status == Status.Handled) {
                    <section class="wow pulse padding-bot20">
                        <h3>博主回应：</h3>
                        <p class="size16">
                            @MvcHtmlString.Create(Model.Msg)
                        </p>
                    </section>
                }
                <!--PC和WAP自适应版-->
                <div id="SOHUCS" sid="bug-@Model.Id"></div>
                <script type="text/javascript">
	                (function() {
		                var appid = 'cytsT3QgK';
		                var conf = 'prod_0358240040a6c9611add9de991099d42';
		                var width = window.innerWidth || document.documentElement.clientWidth;
		                if (width < 960) {
			                window.document.write(
				                '<script id="changyan_mobile_js" charset="utf-8" type="text/javascript" src="https://changyan.sohu.com/upload/mobile/wap-js/changyan_mobile.js?client_id=' +
				                appid + '&conf=' + conf + '"><\/script>');
		                } else {
			                var loadJs = function(d, a) {
				                var c = document.getElementsByTagName("head")[0] || document.head || document.documentElement;
				                var b = document.createElement("script");
				                b.setAttribute("type", "text/javascript");
				                b.setAttribute("charset", "UTF-8");
				                b.setAttribute("src", d);
				                if (typeof a === "function") {
					                if (window.attachEvent) {
						                b.onreadystatechange = function() {
							                var e = b.readyState;
							                if (e === "loaded" || e === "complete") {
								                b.onreadystatechange = null;
								                a()
							                }
						                }
					                } else {
						                b.onload = a
					                }
				                }
				                c.appendChild(b)
			                };
			                loadJs("https://changyan.sohu.com/upload/changyan.js", function() {
				                window.changyan.api.config({
					                appid: appid,
					                conf: conf
				                })
			                });
		                }
	                })();
                </script>
            </div>
        </div>
    </div>
</div>

src/Masuit.MyBlogs.WebApp/Views/Bug/Index.cshtml
@{
    ViewBag.Title = "提交网站漏洞和BUG";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .panel-danger {
        box-shadow: deeppink 0 0 8px;
    }
    .panel-success {
        box-shadow: darkturquoise 0 0 8px;
    }
    .panel-body img{
        max-height: 80px !important;
    }
    .panel-body p{
        word-break: break-all;
    }
</style>
<script src="~/Assets/UEditor/ueditor.config.front.min.js"></script>
<script src="https://apps.bdimg.com/libs/ueditor/1.4.3.1/ueditor.all.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.6/angular.min.js"></script>
<script src="~/Scripts/tm.pagination.js"></script>
<script src="~/Scripts/layer/layer.js"></script>
<div class="container" data-ng-app="myApp" data-ng-controller="home">
    <ol class="cd-breadcrumb triangle">
        <li>@Html.ActionLink("首页", "Index", "Home")</li>
        <li class="current">
            <em>@ViewBag.Title</em>
        </li>
    </ol>
    <div>
        <div class="row">
            <div class="col-sm-6">
                <h3 class="size20" style="line-height: 46px">注意事项：</h3>
            </div>
            <div class="col-sm-6">
                <div class="btn-group pull-right">
                    <button class="btn btn-info btn-lg" type="submit" ng-click="create()">我要提交问题</button>
                </div>
            </div>
        </div>
        <ul class="list-group text-danger">
            <li class="list-group-item">1.本页面不仅仅可以提交本网站的漏洞或者BUG，也可以提交对网站的改进建议或功能完善等等；</li>
            <li class="list-group-item">2.博客文章内容相关的问题，比如链接失效之类的，请直接在文章的评论区反馈即可；</li>
            <li class="list-group-item">3.本博客项目由于是博主个人独立开发，所以漏洞和bug在所难免，而且本项目后期完善以后准备开源，所以大家尽管找bug、提bug，大家共同来完善；</li>
            <li class="list-group-item">4.您提交问题以后，博主会立即收到您的问题，会在最快的时间内修复问题；</li>
            <li class="list-group-item">5.提交后的任何问题都将会立即显示到下方的列表中，如果你发现了致命级别的一些bug，比如：密码泄露、XSS注入等，则需要当问题解决后才会显示到列表中。</li>
        </ul>
    </div>
    <div class="search-form">
        <div class="input-group">
            <input type="text" placeholder="搜索问题、BUG" class="form-control input-lg" ng-model="kw" ng-change="search(kw)">
            <div class="input-group-btn">
                <button class="btn btn-lg btn-primary" type="submit" ng-click="search(kw)">去发现</button>
            </div>
        </div>
    </div>
    <ul class="wow media-list">
        <li class="msg-list media" ng-cloak="" ng-repeat="item in Issues">
            <div class="media-body">
                <article class="panel" ng-class="{true:'panel-success',false:'panel-danger'}[item.Status=='已处理']">
                    <header class="panel-heading">
                        {{item.Name}}({{item.Email}})提交问题：{{item.Title}}【级别：{{item.Level}}】
                        <a ng-href="/bug/{{item.Id}}" class="label" ng-class="{true:'label-success',false:'label-danger'}[item.Status=='已处理']">查看详情</a>
                        <a class="label label-success" ng-if="user.IsAdmin&&item.Status=='待处理'" ng-click="handle(item.Id)">处理完成</a>
                        <a class="label label-info" ng-if="user.IsAdmin" ng-click="delete(item.Id)">删除</a>
                        <span class="pull-right hidden-sm hidden-xs" style="font-size: 14px;">
                            链接地址：
                            <a ng-href="{{item.Link}}">{{item.Link}}</a>
                        </span>
                    </header>
                    <div class="panel-body" ng-bind-html="item.Description|htmlString"></div>
                    <div class="row">
                        <div class="col-sm-4">
                            <span class="label" ng-class="{true:'label-success',false:'label-danger'}[item.Status=='已处理']">
                                <i ng-class="{true:'icon-checkmark',false:'icon-bell'}[item.Status=='已处理']"></i>
                                {{item.Status}}
                            </span>
                        </div>
                        <div class="col-sm-6 pull-right text-right" style="font-size: 8px;margin-top: 3px; margin-right: 3px">
                            <span class="text-danger">提交时间：{{item.SubmitTime|date:'yyyy-MM-dd HH:mm'}}</span>
                            <span class="text-success" ng-if="item.Status=='已处理'">
                                &nbsp;| 处理时间：{{item.HandleTime|date:'yyyy-MM-dd HH:mm'}}
                            </span>
                        </div>
                    </div>
                </article>
            </div>
        </li>
    </ul>
    <tm-pagination conf="paginationConf"></tm-pagination>
    <h2 class="size24 text-primary" ng-if="conf.totalItems <= 0">如此完美？居然没有BUG！！！</h2>
    <div style="position: fixed; left: -20000px; bottom: -20000px;">
        <div id="bug-form" class="container-fluid">
            <form class="form-horizontal margin-top10 margin-bot10" method="post" id="form">
                @Html.AntiForgeryToken()
                <div class="input-group">
                    <span class="input-group-addon">
                        <label for="name">昵称：</label>
                    </span>
                    <input type="text" class="form-control" ng-model="Issue.Name" id="name" required placeholder="昵称" maxlength="16">
                </div>
                <div class="input-group">
                    <span class="input-group-addon">
                        <label for="email">邮箱：</label>
                    </span>
                    <input type="email" class="form-control" ng-model="Issue.Email" id="email" required placeholder="留下您的真实邮箱，以方便接收回复" maxlength="128">
                </div>
                <div class="input-group">
                    <span class="input-group-addon">
                        <label for="title">主题：</label>
                    </span>
                    <input type="text" class="form-control" ng-model="Issue.Title" id="title" required placeholder="是什么问题" maxlength="32">
                </div>
                <div class="input-group">
                    <span class="input-group-addon">
                        <label for="link">链接：</label>
                    </span>
                    <input type="text" class="form-control" ng-model="Issue.Link" id="link" required placeholder="哪个地址出了问题，贴到这里来" maxlength="256">
                </div>
                <div class="input-group">
                    <span class="input-group-addon">
                        <label for="link">BUG级别：</label>
                    </span>
                    <select class="form-control" ng-model="Issue.Level" ng-options="m.value as m.name for m in BugLevels">
                        <option value="">请选择BUG级别</option>
                    </select>
                </div>
                <div class="form-group margin-clear margin-top10">
                    <h3 class="size18">问题的详细描述：</h3>
                    <textarea id="editor" style="height:300px;" class="ueditor" ng-model="Issue.Description" type="text/plain"></textarea>
                </div>
                <div class="btn-group">
                    <button type="button" class="btn btn-info" ng-click="submit(Issue)">
                        提交
                    </button>
                    <button type="button" class="btn btn-danger" ng-click="cancel()">
                        取消
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
<script src="~/Scripts/apps/app.bug.min.js"></script>