src/Masuit.MyBlogs.WebApp/Controllers/MiscController.cs
using System;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web.Mvc;
using Common;
using IBLL;
using Masuit.MyBlogs.WebApp.Models;
using Masuit.Tools;
using Masuit.Tools.Html;
using Masuit.Tools.Net;
using Models.DTO;
using Models.Entity;

namespace Masuit.MyBlogs.WebApp.Controllers
{
    public class MiscController : BaseController
    {
        public IMiscBll MiscBll { get; set; }
        public IDonateBll DonateBll { get; set; }

        public MiscController(IMiscBll miscBll, IDonateBll donateBll)
        {
            MiscBll = miscBll;
            DonateBll = donateBll;
        }

        [Route("misc/{id:int}")]
        public ActionResult Index(int id)
        {
            Misc misc = MiscBll.GetById(id);
            if (misc is null)
            {
                return RedirectToAction("Index", "Error");
            }
            return View(misc);
        }

        [Route("donate")]
        public ActionResult Donate()
        {
            var user = Session.GetByRedis<UserInfoOutputDto>(SessionKey.UserInfo);
            if (user != null && user.IsAdmin)
            {
                return View("Donate_Admin");
            }
            return View();
        }

        [Route("donatelist")]
        public ActionResult DonateList(int page = 1, int size = 10)
        {
            var list = DonateBll.LoadPageEntitiesFromL2CacheNoTracking(page, size, out int total, d => true, d => d.DonateTime, false).Select(d => new
            {
                d.NickName,
                d.EmailDisplay,
                d.QQorWechatDisplay,
                d.DonateTime,
                d.Amount,
                d.Via
            }).ToList();
            var pageCount = Math.Ceiling(total * 1.0 / size).ToInt32();
            return PageResult(list, pageCount, total);
        }

        [Route("about")]
        public ActionResult About()
        {
            return View();
        }

        [Route("disclaimer")]
        public ActionResult Disclaimer()
        {
            return View();
        }

        [ValidateInput(false), Authority]
        public ActionResult Write(Misc model)
        {
            model.Content = CommonHelper.ReplaceImgSrc(Regex.Replace(model.Content?.Trim(), @"<img\s+[^>]*\s*src\s*=\s*['""]?(\S+\.\w{3,4})['""]?[^/>]*/>", "<img src=\"$1\"/>")).Replace("/thumb150/", "/large/");
            var e = MiscBll.AddEntitySaved(model);
            if (e != null)
            {
                return ResultData(null, message: "发布成功");
            }
            return ResultData(null, false, "发布失败");
        }

        [Authority]
        public ActionResult Delete(int id)
        {
            var post = MiscBll.GetById(id);
            if (post is null)
            {
                return ResultData(null, false, "杂项页已经被删除！");
            }

            var mc = post.Content.MatchImgTags();
            foreach (Match m in mc)
            {
                string path = m.Groups[3].Value;
                if (path.StartsWith("/"))
                {
                    path = Path.Combine(Server.MapPath("/"), path);
                    try
                    {
                        System.IO.File.Delete(path);
                    }
                    catch (IOException)
                    {
                    }
                }
            }
            bool b = MiscBll.DeleteByIdSaved(id);
            return ResultData(null, b, b ? "删除成功" : "删除失败");
        }

        [ValidateInput(false), Authority]
        public ActionResult Edit(Misc misc)
        {
            var entity = MiscBll.GetById(misc.Id);
            entity.ModifyDate = DateTime.Now;
            entity.Title = misc.Title;
            entity.Content = CommonHelper.ReplaceImgSrc(Regex.Replace(misc.Content, @"<img\s+[^>]*\s*src\s*=\s*['""]?(\S+\.\w{3,4})['""]?[^/>]*/>", "<img src=\"$1\"/>")).Replace("/thumb150/", "/large/");
            bool b = MiscBll.UpdateEntitySaved(entity);
            return ResultData(null, b, b ? "修改成功" : "修改失败");
        }

        [Authority]
        public ActionResult GetPageData(int page = 1, int size = 10)
        {
            var list = MiscBll.LoadPageEntitiesNoTracking(page, size, out int total, n => true, n => n.ModifyDate, false).Select(m => new
            {
                m.Id,
                m.Title,
                m.ModifyDate,
                m.PostDate
            }).ToList();
            var pageCount = Math.Ceiling(total * 1.0 / size).ToInt32();
            return PageResult(list, pageCount, total);
        }

        [Authority]
        public ActionResult Get(int id)
        {
            var notice = MiscBll.GetById(id);
            return ResultData(notice.MapTo<MiscOutputDto>());
        }
    }
}

src/Masuit.MyBlogs.WebApp/Controllers/ToolsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Mvc;
using Masuit.Tools.Models;
using Masuit.Tools.Net;
#if DEBUG
using Masuit.Tools.Win32;
#endif
using Newtonsoft.Json;
using Quartz;
using Quartz.Spi;

namespace Masuit.MyBlogs.WebApp.Controllers
{
    [RoutePrefix("tools")]
    public class ToolsController : BaseController
    {
        [HttpGet, Route("ip/{ip?}")]
        public async Task<ActionResult> GetIpInfo(string ip)
        {
            if (string.IsNullOrEmpty(ip))
            {
                ip = Request.UserHostAddress;
            }
            ViewBag.IP = ip;
            PhysicsAddress address = await ip.GetPhysicsAddressInfo();
            if (Request.HttpMethod.ToLower().Equals("get"))
            {
                return View(address);
            }
            return Json(address);
        }

        [HttpGet, Route("pos")]
        public async Task<ActionResult> Position(string lat, string lng)
        {
            if (string.IsNullOrEmpty(lat) || string.IsNullOrEmpty(lng))
            {
                var ip = Request.UserHostAddress;
#if DEBUG
                Random r = new Random();
                ip = $"{r.StrictNext(210)}.{r.StrictNext(255)}.{r.StrictNext(255)}.{r.StrictNext(255)}";
#endif
                PhysicsAddress address = await ip.GetPhysicsAddressInfo();
                return View(address);
            }
            using (HttpClient client = new HttpClient()
            {
                BaseAddress = new Uri("http://api.map.baidu.com")
            })
            {
                var s = await client.GetStringAsync($"/geocoder/v2/?location={lat},{lng}&output=json&pois=1&ak={ConfigurationManager.AppSettings["BaiduAK"]}");
                PhysicsAddress physicsAddress = JsonConvert.DeserializeObject<PhysicsAddress>(s);
                return View(physicsAddress);
            }
        }

        [HttpGet, Route("addr")]
        public async Task<ActionResult> Address(string addr)
        {
            if (string.IsNullOrEmpty(addr))
            {
                var ip = Request.UserHostAddress;
#if DEBUG
                Random r = new Random();
                ip = $"{r.StrictNext(210)}.{r.StrictNext(255)}.{r.StrictNext(255)}.{r.StrictNext(255)}";
#endif
                PhysicsAddress address = await ip.GetPhysicsAddressInfo();
                if (address.Status == 0)
                {
                    ViewBag.Address = address.AddressResult.FormattedAddress;
                    if (Request.HttpMethod.ToLower().Equals("get"))
                    {
                        return View(address.AddressResult.Location);
                    }
                    return Json(address.AddressResult.Location);
                }
            }
            ViewBag.Address = addr;
            using (HttpClient client = new HttpClient()
            {
                BaseAddress = new Uri("http://api.map.baidu.com")
            })
            {
                var s = await client.GetStringAsync($"/geocoder/v2/?output=json&address={addr}&ak={ConfigurationManager.AppSettings["BaiduAK"]}");
                var physicsAddress = JsonConvert.DeserializeAnonymousType(s, new
                {
                    status = 0,
                    result = new
                    {
                        location = new Location()
                    }
                });
                if (Request.HttpMethod.ToLower().Equals("get"))
                {
                    return View(physicsAddress.result.location);
                }
                return Json(physicsAddress.result.location);
            }
        }

        [Route("vip")]
        public ActionResult Videos()
        {
            return View();
        }

        public ActionResult Cron()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cron(string cron)
        {
            //时间表达式
            ITrigger trigger = TriggerBuilder.Create().WithCronSchedule(cron).Build();
            IList<DateTimeOffset> dates = TriggerUtils.ComputeFireTimes(trigger as IOperableTrigger, null, 5);
            List<string> list = new List<string>();
            foreach (DateTimeOffset dtf in dates)
            {
                list.Add(TimeZoneInfo.ConvertTimeFromUtc(dtf.DateTime, TimeZoneInfo.Local).ToString());
            }
            if (list.Any())
            {
                return ResultData(list);
            }
            list.Add($"{cron} 不是合法的cron表达式");
            return ResultData(list);
        }
    }
}

src/Masuit.MyBlogs.WebApp/Views/Tools/Address.cshtml
@using Masuit.Tools.Models
@model Location
@{
    ViewBag.Title = "根据详细地理位置信息获取经纬度";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    #allmap {
        height: 900px;
        width: 100%;
    }
</style>
<div class="container">
    <ol class="cd-breadcrumb triangle">
        <li>@Html.ActionLink("首页", "Index", "Home")</li>
        <li class="current">
            <em>@ViewBag.Title</em>
        </li>
    </ol>
        <ul class="list-group">
            <li class="list-group-item">
                <p class="size24">
                    如果你觉得这个工具有用，请 @Html.ActionLink("点击这里", "Donate", "Misc") 支持一下博主！
                </p>
            </li>
        </ul>
    <form method="get">
        <div class="input-group">
            <input class="form-control" name="addr" value="@ViewBag.Address" placeholder="请输入有效地理位置" />
            <span class="input-group-btn">
                <button class="btn btn-info" type="submit">查询</button>
            </span>
        </div>
    </form>
    @if (Model != null)
    {
        <table class="table table-bordered table-condensed table-hover">
            <tr>
                <td>经纬度：</td>
                <td>(经度：@(Model.Lng),纬度：@(Model.Lat))</td>
            </tr>
        </table>
    }
</div>
<div class="container-fluid">
    @if (Model != null)
    {
        <div id="allmap"></div>
        <script type="text/javascript" src="https://api.map.baidu.com/api?v=2.0&ak=89772e94509a9b903724e247cbc175c2"></script>
        <script>
	    var map = new BMap.Map("allmap"); // 创建Map实例,设置地图允许的最小/大级别

	    map.centerAndZoom(new BMap.Point(@(Model.Lng), @(Model.Lat)), 16);
	    map.enableScrollWheelZoom(true);
	    map.clearOverlays();
	    var new_point = new BMap.Point(@(Model.Lng), @(Model.Lat));
	    var marker = new BMap.Marker(new_point); // 创建标注
	    map.addOverlay(marker); // 将标注添加到地图中
	    marker.setAnimation(BMAP_ANIMATION_BOUNCE); //跳动的动画
	    map.panTo(new_point);
        </script>
    }
</div>

src/Masuit.MyBlogs.WebApp/Views/Tools/GetIPInfo.cshtml
@using Masuit.Tools.Models
@model PhysicsAddress
@{
    ViewBag.Title = "获取IP地址详细地理位置信息";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    #allmap {
        height: 900px;
        width: 100%;
    }
</style>
<div class="container">
    <ol class="cd-breadcrumb triangle">
        <li>@Html.ActionLink("首页", "Index", "Home")</li>
        <li class="current">
            <em>@ViewBag.Title</em>
        </li>
    </ol>
        <ul class="list-group">
            <li class="list-group-item">
                <p class="size24">
                    如果你觉得这个工具有用，请 @Html.ActionLink("点击这里", "Donate", "Misc") 支持一下博主！
                </p>
            </li>
        </ul>
    <form method="get">
        <div class="input-group">
            <input class="form-control" name="ip" value="@ViewBag.IP" placeholder="请输入有效的IPv4地址"/>
            <span class="input-group-btn">
                <button class="btn btn-info" type="submit">查询</button>
            </span>
        </div>
    </form>
    @if(Model != null && Model.Status == 0) {
        int count = 0;
        <table class="table table-bordered table-condensed table-hover">
            <tr>
                <td>参考地理位置：</td>
                <td>@Model.AddressResult.FormattedAddress</td>
            </tr>
            <tr>
                <td>标志性商业街：</td>
                <td>@Model.AddressResult.Business</td>
            </tr>
            <tr>
                <td>经纬度：</td>
                <td>(经度：@(Model.AddressResult.Location?.Lng),纬度：@(Model.AddressResult.Location?.Lat))</td>
            </tr>
            @foreach(Pois poi in Model.AddressResult.Pois) {
                <tr>
                    <td>参考地理位置@(++count)：</td>
                    <td>@poi.AddressDetail</td>
                </tr>
            }
        </table>
        
    } else {
        <span class="text-danger">@ViewBag.IP 不在国内或者不是一个有效的IPv4外网地址</span>
    }
</div>
<div class="container-fluid">
    @if (Model != null && Model.Status == 0)
    {
        <div id="allmap"></div>
        <script type="text/javascript" src="https://api.map.baidu.com/api?v=2.0&ak=89772e94509a9b903724e247cbc175c2"></script>
        <script>
	    var map = new BMap.Map("allmap"); // 创建Map实例,设置地图允许的最小/大级别

	    map.centerAndZoom(new BMap.Point(@(Model.AddressResult.Location?.Lng), @(Model.AddressResult.Location?.Lat)), 16);
	    map.enableScrollWheelZoom(true);
	    map.clearOverlays();
	    var new_point = new BMap.Point(@(Model.AddressResult.Location?.Lng), @(Model.AddressResult.Location?.Lat));
	    var marker = new BMap.Marker(new_point); // 创建标注
	    map.addOverlay(marker); // 将标注添加到地图中
	    marker.setAnimation(BMAP_ANIMATION_BOUNCE); //跳动的动画
	    map.panTo(new_point);
        </script>
    }
</div>

src/Masuit.MyBlogs.WebApp/Views/Tools/Position.cshtml
@using Masuit.Tools.Models
@model PhysicsAddress

@{
    ViewBag.Title = "根据经纬度查询详细地理位置";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    #allmap {
        height: 900px;
        width: 100%;
    }
</style>
<div class="container">
    <ol class="cd-breadcrumb triangle">
        <li>@Html.ActionLink("首页", "Index", "Home")</li>
        <li class="current">
            <em>@ViewBag.Title</em>
        </li>
    </ol>
        <ul class="list-group">
            <li class="list-group-item">
                <p class="size24">
                    如果你觉得这个工具有用，请 @Html.ActionLink("点击这里", "Donate", "Misc") 支持一下博主！
                </p>
            </li>
        </ul>
    @if (Model != null && Model.Status == 0)
    {
        <form method="get">
            <div class="row">
                <div class="col-md-5">
                    <div class="input-group">
                        <span class="input-group-addon">经度：</span>
                        <input class="form-control" name="lng" value="@(Model.AddressResult.Location?.Lng)" placeholder="请输入经度值" />
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="input-group">
                        <span class="input-group-addon">纬度：</span>
                        <input class="form-control" name="lat" value="@(Model.AddressResult.Location?.Lat)" placeholder="请输入纬度值" />
                    </div>
                </div>
                <div class="col-md-1">
                    <div class="input-group">
                        <button class="btn btn-info" type="submit">查询</button>
                    </div>
                </div>
            </div>
        </form>
        int count = 0;
        <table class="table table-bordered table-condensed table-hover">
            <tr>
                <td>参考地理位置：</td>
                <td>@Model.AddressResult.FormattedAddress</td>
            </tr>
            <tr>
                <td>标志性商业街：</td>
                <td>@Model.AddressResult.Business</td>
            </tr>
            <tr>
                <td>经纬度：</td>
                <td>(经度：@(Model.AddressResult.Location?.Lng),纬度：@(Model.AddressResult.Location?.Lat))</td>
            </tr>
            @foreach (Pois poi in Model.AddressResult.Pois)
            {
                <tr>
                    <td>参考地理位置@(++count)：</td>
                    <td>@poi.AddressDetail</td>
                </tr>
            }
        </table>

    }
    else
    {
        <form method="get">
            <div class="row">
                <div class="col-md-5">
                    <div class="input-group">
                        <span class="input-group-addon">经度：</span>
                        <input class="form-control" name="lng" placeholder="请输入经度值" />
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="input-group">
                        <span class="input-group-addon">纬度：</span>
                        <input class="form-control" name="lat" placeholder="请输入纬度值" />
                    </div>
                </div>
                <div class="col-md-1">
                    <div class="input-group">
                        <button class="btn btn-info" type="submit">查询</button>
                    </div>
                </div>
            </div>
        </form>
    }
</div>
<div class="container-fluid">
    @if (Model != null && Model.Status == 0)
    {
        <div id="allmap"></div>
        <script type="text/javascript" src="https://api.map.baidu.com/api?v=2.0&ak=89772e94509a9b903724e247cbc175c2"></script>
        <script>
	    var map = new BMap.Map("allmap"); // 创建Map实例,设置地图允许的最小/大级别

	    map.centerAndZoom(new BMap.Point(@(Model.AddressResult.Location?.Lng), @(Model.AddressResult.Location?.Lat)), 16);
	    map.enableScrollWheelZoom(true);
	    map.clearOverlays();
	    var new_point = new BMap.Point(@(Model.AddressResult.Location?.Lng), @(Model.AddressResult.Location?.Lat));
	    var marker = new BMap.Marker(new_point); // 创建标注
	    map.addOverlay(marker); // 将标注添加到地图中
	    marker.setAnimation(BMAP_ANIMATION_BOUNCE); //跳动的动画
	    map.panTo(new_point);
        </script>
    }
</div>

src/Masuit.MyBlogs.WebApp/Views/Tools/Videos.cshtml
@{
    ViewBag.Title = "全网VIP视频在线破解！";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var url = string.IsNullOrEmpty(Request["v"]) ? "http://v.youku.com/v_show/id_XMzA4MjMyOTA1Ng==.html" : Request["v"];
}
<div class="container-fluid">
    <ol class="cd-breadcrumb triangle">
        <li>@Html.ActionLink("首页", "Index", "Home")</li>
        <li class="current">
            <em>@ViewBag.Title</em>
        </li>
    </ol>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading">操作指南：</div>
                <div class="panel-body">
                    <p>第 一 步 进入各大视频网站，找到想要观看的VIP视频，然后复制链接（浏览器上的视频地址）</p>
                    <p>第 二 步 将复制的链接粘贴到本站播放地址，并点击开始解析</p>
                    <p>第 三 步 等待解析完成，即可免费观看VIP视频</p>
                    <p>免费全网VIP视频会员免广告看电影！亲们如果觉得好用，请帮我们传播！ 若播放异常，刷新，更换接口尝试哦！</p>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading">温馨提示：</div>
                <div class="panel-body">
                    <ul class="list-group">
                        <li class="list-group-item">支持全网VIP视频解析，但不保证所有的线路都能正常解析</li>
                        <li class="list-group-item">如果遇到无法播放 切换播放通道 不同的网站可能跟解析服务器支持有关</li>
                        <li class="list-group-item">这些接口来源于网络泄露特别是会员解析通道 低调使用 我会定期更新</li>
                        <li class="list-group-item">如果视频不能正常播放，请尝试更换线路，建议多切换几个线路尝试，理论上总是能够播放成功的！</li>
                        <li class="list-group-item">本站不提供解析服务，接口源于互联网，仅供学习交流，请勿用于商业，后果自负！已支持以下网站视频播放(包含VIP电影)</li>
                        <li>
                            <img class="img-thumbnail img-responsive" src="~/Assets/images/video.jpg" />
                        </li>
                        <li class="list-group-item">
                            <p class="size24">
                                如果你觉得这个工具有用，请 @Html.ActionLink("点击这里", "Donate", "Misc") 支持一下博主！
                            </p>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <div class="input-group">
                <span class="input-group-addon">
                    视频地址(URL)：
                </span>
                <input type="url" class="form-control input-lg" id="url" value="@url" placeholder="请将需要VIP的视频地址复制粘贴到这里"/>
            </div>
        </div>
        <div class="col-md-4">
            <div class="input-group">
                <span class="input-group-addon">
                    解析路线：
                </span>
                <select class="form-control input-lg" id="route">
                    <option value="http://api.baiyug.cn/vip/index.php?url=">默认线路</option>
                    <option value="http://api.1008net.com/v.php?url=">线路1</option>
                    <option value="http://api.nepian.com/ckparse/?url=" selected="selected">线路2</option>
                    <option value="http://player.jidiaose.com/supapi/iframe.php?v=">线路3</option>
                    <option value="http://api.pucms.com/index.php?url=">线路4</option>
                    <option value="http://api.wlzhan.com/sudu/?url=">线路5</option>
                    <option value="http://www.0335haibo.com/yun.php?url=">线路6</option>
                    <option value="http://yun.mt2t.com/yun?url=">线路7</option>
                    <option value="http://y.mt2t.com/lines?url=">线路8</option>
                    <option value="http://www.sfsft.com/video.php?url=">线路9</option>
                    <option value="http://www.82190555.com/video.php?url=">线路10</option>
                    <option value="http://2.jx.72du.com/video.php?url=">线路11</option>
                    <option value="http://www.97panda.com/kkflv/index.php?url=">线路12</option>
                    <option value="http://jx.vgoodapi.com/jx.php?url=">线路13</option>
                    <option value="http://www.dgua.xyz/webcloud/?url=">线路14</option>
                    <option value="http://api.91exp.com/svip/?url=">线路15</option>
                    <option value="http://vip.jlsprh.com/index.php?url=">线路16</option>
                    <option value="http://api.xfsub.com/index.php?url=">线路17</option>
                    <option value="http://jiexi.92fz.cn/player/vip.php?url=">线路18</option>
                    <option value="http://api.baiyug.cn/vip/index.php?url=">线路19</option>
                    <option value="http://api.662820.com/xnflv/index.php?url=">线路20</option>
                    <option value="http://www.82190555.com/index/qqvod.php?url=">线路21</option>
                    <option value="http://yyygwz.com/index.php?url=">线路22</option>
                    <option value="http://www.97panda.com/kkflv/index.php?url=">线路23</option>
                    <option value="http://jx.api.163ren.com/vod.php?url=">线路24</option>
                    <option value="http://lookxw.com/yingzi/?url=">线路25</option>
                    <option value="http://www.0335haibo.com/tong.php?url=">线路26</option>
                    <option value="http://www.wmxz.wang/video.php?url=">线路27</option>
                    <option value="http://api.97kn.com/?url=">线路28</option>
                    <option value="https://aikanapi.duapp.com/odflv105/index.php?url=">线路29</option>
                    <option value="http://v.buy360.vip/wwcx/index.php?url=">线路30</option>
                    <option value="http://api.lequgirl.com/?url=">线路31</option>
                    <option value="https://jxapi.nepian.com/ckparse/?url=">线路32</option>
                    <option value="http://91k.co/play.php?url=">线路33</option>
                    <option value="http://www.52jiexi.com/yun.php?url=">线路34</option>
                    <option value="http://mt2t.com/yun?url=">线路35</option>
                    <option value="http://000o.cc/jx/ty.php?url=">线路36</option>
                    <option value="http://yyygwz.com/index.php?url=">线路37</option>
                    <option value="http://vipjiexi.com/vip.php?url=">线路38</option>
                    <option value="http://www.wmxz.wang/video.php?url=">线路39</option>
                    <option value="http://jx.ck921.com/?url=">线路40</option>
                    <option value="http://s1y2.com/?url=">线路41</option>
                    <option value="http://www.ou522.cn/t2/1.php?url=">线路42</option>
                    <option value="http://jx.xuanpianwang.com/parse?url=">线路43</option>
                    <option value="https://apiv.ga/magnet/">线路44</option>
                    <option value="http://jiexi.92fz.cn/player/vip.php?url=">线路45</option>
                </select>
                <span class="input-group-btn">
                    <button class="btn btn-info btn-lg" id="play">开始播放</button>
                </span>
            </div>
        </div>
    </div>
    <iframe src="" frameborder="0" width="100%" id="video" style="height: 85vh;"></iframe>
</div>
<script>
	$(function() {
		$("#play").on("click", function(e) {
			$("#video").attr("src", $("#route").val() + $("#url").val());
        });
		$("#route").on("change", function(e) {
			$("#video").attr("src", $("#route").val() + $("#url").val());
		});
	});
</script>